k3s_cluster:
  children:
    k3sleaders:
      hosts:
        leader01:
          ansible_host: leader01
      vars:
        ansible_user: pi
    k3sfollowers:
      hosts:
        follower01:
          ansible_host: follower01
        follower02:
          ansible_host: follower03
      vars:
        ansible_user: pi