k3s_cluster:
  children:
    k3sleaders:
      hosts:
        leader01:
          ansible_host: leader01.local
          ansible_user: "{{ inventory_hostname }}"
    k3sfollowers:
      hosts:
        follower01:
          ansible_host: follower01.local
          ansible_user: "{{ inventory_hostname }}"
        follower02:
          ansible_host: follower02.local
          ansible_user: "{{ inventory_hostname }}"
        follower03:
          ansible_host: follower03.local
          ansible_user: "{{ inventory_hostname }}"
