k3s_cluster:
  children:
    k3sleaders:
      hosts:
        leader01:
          ansible_host: 192.168.0.12
          ansible_user: "{{ inventory_hostname }}"
    k3sfollowers:
      hosts:
        follower01:
          ansible_host: 192.168.0.11
          ansible_user: "{{ inventory_hostname }}"
        # Pending microSD reflash (add back when cards arrive):
        # follower02:
        #   ansible_host: 192.168.0.10
        #   ansible_user: "{{ inventory_hostname }}"
        # follower03:
        #   ansible_host: 192.168.0.9
        #   ansible_user: "{{ inventory_hostname }}"
