---
- name: Get the latest stable version of k3s
  ansible.builtin.command: curl -s https://api.github.com/repos/k3s-io/k3s/releases/latest
  delegate_to: localhost
  become: false
  register: k3s_latest_release
  when: k3s_use_latest_version | default(false) | bool

- name: Parse JSON output and set k3s_version
  ansible.builtin.set_fact:
    k3s_version: "{{ (k3s_latest_release.stdout | from_json).tag_name }}"
  when: k3s_use_latest_version | default(false) | bool

- name: Use pinned k3s_version from inventory
  ansible.builtin.debug:
    msg: "Using pinned k3s_version={{ k3s_version }}"
  when: not (k3s_use_latest_version | default(false) | bool)
