---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3sleaders'][0]]['ansible_host'] | default(groups['k3sleaders'][0]) }}"
extra_server_args: ""
extra_agent_args: ""